name: Auto-reply to new issues

on:
  issues:
    types: [opened]

jobs:
  auto_reply:
    runs-on: ubuntu-latest
    steps:
    - name: Post auto-reply comment
      uses: cj-mills/auto-reply-workflow@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
